version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    ports:
      - "80:80"
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    image: php:fpm
    volumes:
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./wordpress:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


